spring:
  application:
    name: msmarvel
  datasource:
    url: jdbc:h2:mem:hero_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: msmarvel
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
